version: "2"
services:
 web:
  container_name: nginx
  restart: always
  build: nginx
  ports:
   - "8080:80"
  links:
   - app

 app:
  container_name: app
  restart: always
  build: app
  expose:
   - "4000"
  links:
   - mongo
  depends_on:
   - "mongo"
  restart: unless-stopped

 mongo:
  container_name: mongo
  image: mongo
  expose:
   - "27017"
  volumes:
   - ./db:/data/db
